services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  interviewai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interviewai
    ports:
      - "80:80"
    depends_on:
      - redis
