services:
  interviewai-redis:
    image: redis:latest
    container_name: interviewai-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  interviewai-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interviewai-web
    ports:
      - "3000:3000"
    depends_on:
      - interviewai-redis
